### PR TITLE
Update sentence_translations.json

### PR DESCRIPTION
**Pull request by rajeshwar-pandey**
There is a major case of diglossia among people that know Hindi, which is why I have incorporated multiple words of the same meaning at various junctures to keep any potential listener in the know. So, if you run these translations through a translator, you might see the same word appearing twice in a sentence for this very reason.

### CODE REVIEW

**Comment by 3b1b** [comment]
Very interesting. And just to check, do you think having multiple words like this sound natural when spoken?

**Comment by rajeshwar-pandey** [comment]
> Very interesting. And just to check, do you think having multiple words like this sounds natural when spoken?

It would because you are explaining mathematical concepts to the people. One of the key differences I have noticed while attending lectures in both Hindi and English is that Hindi lectures go slower for this reason. The Hindi in use needs to be simple and precise, whereas English vocabulary has a greater reach among students attending those lectures so they flow quicker.

**Comment by saurabh-git-dev** [comment]
> Very interesting. And just to check, do you think having multiple words like this sounds natural when spoken?

described in a very good and simple way. Used simple words of day-to-day life. We use the same words when we study in Hindi.

**Comment by saurabh-git-dev** [comment]
@3b1b It would be great if we could see what people are working on. **Possibility of duplicate work**. 
I did the translation of the same one of the short video captions which is done by @rajeshwar-pandey. But I found it late. But it is better than me. So I closed my PR.
I would like to contribute. And I am also working on a long video.

**Comment by rajeshwar-pandey** [comment]
> @3b1b It would be great if we could see what people are working on. **Possibility of duplicate work**. I did the translation of the same one of the short video captions which is done by @rajeshwar-pandey. But I found it late. But it is better than me. So I closed my PR. I would like to contribute. And I am also working on a long video.

Thank you for the compliment. I agree with the suggestion of somehow coordinating this to avoid duplication. Also, I would like to know which video you are working on currently, so I don't accidentally end up duplicating it again.

**Comment by saurabh-git-dev** [comment]
[https://github.com/3b1b/captions/tree/main/2023/prism/hindi](https://github.com/3b1b/captions/tree/main/2023/prism/hindi)

**Comment by 3b1b** [comment]
> @3b1b It would be great if we could see what people are working on. **Possibility of duplicate work**. I did the translation of the same one of the short video captions which is done by @rajeshwar-pandey. But I found it late. But it is better than me. So I closed my PR. I would like to contribute. And I am also working on a long video.

Completely agree. I just set up a discord that we can maybe start using for this: https://discord.gg/MSKzxDgTGE

**Pull request merged**
