### PR TITLE
Add upload button

### PR DESCRIPTION
**Pull request by vincerubinetti**
@FaboBence Please test the upload feature in the Netlify preview link below.

- move "insufficient file" error to top of create pr script, so the error is discovered early, before branch is created
- re-run update.ts script to fill in more lesson full titles
- fix bug where submitting empty files would throw error
- add ability to upload previously downloaded zip
- make more comprehensive pre-populated issue links
- add "view raw json" button with link to line number
- fix case sensitivity bug in homepage lesson name search

### CODE REVIEW

**Comment by FaboBence** [comment]
I have tested the described functionality with main focus on the ZIP uploads. It's working well!

**Comment by 3b1b** [comment]
It looks reasonable to me, and appears to work when I test it.

**Comment by 3b1b** [comment]
Any objection if I merge?

**Comment by vincerubinetti** [comment]
Good to go

**Pull request merged**
