### PR TITLE
[CI] Language labeler

### LINKED ISSUE #43: Suggestion: Language labels
We should make it easier to know the language of each pull request for smoother reviews. 

While some mention it in the title, enforcing a format can be tricky. A simple solution could be using labels, automatically set by the [labeler action](https://github.com/actions/labeler). For example, a PR changing `https://github.com/3b1b/captions/blob/main/2023/ego-and-math/spanish/sentence_translations.json` could be labeled as 'Spanish' since it's in the 'spanish' directory, and the same for the other languages.

If you agree, I can submit a PR for this.

### PR DESCRIPTION
**Pull request by Yag000**
Closes #43 

## Labeler

This pull request introduces a simple language labeler. For each pull request, an automated action is triggered to add the corresponding language label based on the directory containing the modified files. The labeler checks the directory for known languages and adds the appropriate label accordingly.

As language options may evolve over time (currently limited to those corresponding to Discord channels), a script has been implemented to dynamically generate the configuration file `.github/labeler.sh`. By adding a language to the configuration file and executing the script the configuration file will be update to keep track of that language.

## Example
In [this pull request](https://github.com/Yag000/captions/pull/3), the file `2016/brachistochrone/chinese/sentence_translations.json` was modified. Since it resides in a directory named `chinese`, the labeler added the `Chinese` label to the pull request.
image

### CODE REVIEW

**Comment by Yag000** [comment]
The labeler uses this [action](https://github.com/actions/labeler) and gets triggered by `pull_request_target`, which is described [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

**Comment by 3b1b** [comment]
Thanks for this. Can you think of a nice way to avoid hardcoding in the list of languages? Perhaps if any of the files changed exist in a directory with the pattern "**/{year}/{video-id}/{language_name}" or " "**/{year}/shorts/{video-id}/{language_name}" the label for language_name is generated.

Also, are there any nice Github features creating a better default title for the PR?

**Comment by Yag000** [comment]
> Thanks for this. Can you think of a nice way to avoid hardcoding in the list of languages? Perhaps if any of the files changed exist in a directory with the pattern "**/{year}/{video-id}/{language_name}" or " "**/{year}/shorts/{video-id}/{language_name}" the label for language_name is generated.

I'll look into it. I'm not sure if GitHub's labeler action allows that (I believe not), but I'll try to find more about it. If not, I can try and create a more specific action for this project.

> Also, are there any nice Github features creating a better default title for the PR?

The first thing that comes to mind is [issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). They are quite powerful and might be what we need. Could you share your thoughts on what you have in mind for the PR titles?

**Comment by 3b1b** [comment]
What would be nice is if, by default, the PR title showed the language, which video, and whether it was a review of the transcript, the title, the description, or some subset therein.

**Comment by Yag000** [comment]
> What would be nice is if, by default, the PR title showed the language, which video, and whether it was a review of the transcript, the title, the description, or some subset therein.

Okay, I'll look into that tomorrow if I find the time.

As for the automatic labeling, I encountered some issues. Implementing an entirely new action would be too extensive, requiring more time than I currently have available. However, we can easily address the hardcoded languages in the script by dynamically generating the configuration file based on the languages present in the repository (I'll push this update soon). The only drawback is that adding a new language would necessitate a commit to update the config file, involving running the script and committing the changes. Currently, there are 46 different languages in the repo, making it unlikely for a new language to be added frequently. We could opt to keep it as is and handle the update with a simple commit whenever necessary.

We could also try to automate it. A quick solution would be to create an action that checks for new languages (executing the script and using `git diff`) and then either pushes the updated config file or creates a pull request with the changes (a safer option). This is far from ideal, but it is the simplest approach I can think of for now.  The biggest issue with this approach is that we would need to specify a name + email for the committer, we could use yours, mine, `github-actions` or something like that. I'm not a big fan of this solution, I think that manual is more reasonable for now.

**Comment by 3b1b** [comment]
That works for me. You're right, adding new languages would not be frequent. Do you feel good about me merging this?

**Comment by Yag000** [comment]
I've just added some documentation for the regex in the script and restricted the year to only match numbers in the range [2000, 2099] to avoid potential collisions with non-video directories in the future. For me, it's now good to merge :)

**Comment by 3b1b** [comment]
Thank you!

**Pull request merged**
